name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Install Dotnet 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore ./Employee/

      - name: Build Solution
        run: dotnet build ./Employee/

      - name: Run Tests
        run: dotnet test ./Employee/Employee.WebAPITests/
